[package]
name            = "disktest"
description     = "Hard Disk and Solid State Disk tester"
version         = "1.0.0"
edition         = "2018"
homepage        = "https://bues.ch/h/disktest"
license         = "GPL-2.0-or-later"
readme          = "README.rst"
repository      = "https://git.bues.ch/git/disktest.git"
authors         = ["Michael Buesch <m@bues.ch>"]

categories      = ["command-line-utilities", "filesystem", "hardware-support"]
keywords        = ["disk", "HDD", "SSD", "flash", "SD-card"]

exclude         = ["/maintenance/", "/testfile*"]

[dependencies]
clap            = "2.33.3"
crc             = "1.8.1"
libc            = "0.2.79"
num_cpus        = "1.13.0"
rust-crypto     = "0.2.36"
signal-hook     = "0.1.16"
tempfile        = "3.1.0"

[profile.release]
lto             = "thin"
panic           = "abort"

[profile.bench]
lto             = "thin"

# vim: ts=4 sw=4 expandtab
