[package]
name		= "disktest"
version		= "1.0.0"
authors		= ["Michael Buesch <m@bues.ch>"]
edition		= "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap		= "2.33.3"
crc		= "1.8.1"
libc		= "0.2.79"
num_cpus	= "1.13.0"
rust-crypto	= "0.2.36"
signal-hook	= "0.1.16"
tempfile	= "3.1.0"

[profile.release]
lto		= "thin"
panic		= "abort"

[profile.bench]
lto		= "thin"
