[package]
name = "disktest"
version = "1.0.0"
authors = ["Michael Buesch <m@bues.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sha2 = "0.8.0"
clap = "2.33.3"
